### ISSUE TITLE
[future branch] YggdrasilgetPeersJSON() native method returns null

### ISSUE THREAD

**Issue by vikulin** [yggdrasil-network/yggdrasil-extras#10]
YggdrasilgetPeersJSON() native method returns null for yggdrasil class instance. this corresponds to 

https://github.com/yggdrasil-network/yggdrasil-extras/blob/future/src/mobile/mobile.go#L132

**Comment by vikulin** [comment]
Log:
```
I/Yggdrasil: Start
I/GoLog: Build name: yggdrasil-future
    Build version: 0.4.0rc2-20-g1083131
    Starting up...
I/GoLog: Startup complete
I/GoLog: Starting multicast module
I/TetheringManager: registerTetheringEventCallback:io.github.chronosx88.yggdrasil
D/Yggdrasil: Update Peers
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.chronosx88.yggdrasil, PID: 4704
    java.lang.RuntimeException: Unable to start service io.github.chronosx88.yggdrasil.YggdrasilTunService@691c422 with Intent { cmp=io.github.chronosx88.yggdrasil/.YggdrasilTunService (has extras) }: java.lang.NullPointerException: gson.fromJson(ygg.peersJSON, Token().type) must not be null
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4344)
        at android.app.ActivityThread.access$1800(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: gson.fromJson(ygg.peersJSON, Token().type) must not be null
        at io.github.chronosx88.yggdrasil.YggdrasilTunService.sendMeshPeerStatus(YggdrasilTunService.kt:142)
        at io.github.chronosx88.yggdrasil.YggdrasilTunService.onStartCommand(YggdrasilTunService.kt:68)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4326)
        at android.app.ActivityThread.access$1800(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
D/Yggdrasil: Update Peers
D/Yggdrasil: Update Peers
D/Yggdrasil: Update Peers
D/Yggdrasil: Update Peers
```

**Comment by vikulin** [comment]
Closed.
