### ISSUE TITLE
App crashes while Yggdrasil.recv() method call

### ISSUE THREAD

**Issue by vikulin** [yggdrasil-network/yggdrasil-extras#12]
App crashes while Yggdrasil.recv() method call:
```
go.Universe$proxyerror: invalid destination address
	at mobile.Yggdrasil.send(Native Method)
	at io.github.chronosx88.yggdrasil.YggdrasilTunService.readPacketsFromTun(YggdrasilTunService.kt:204)
	at io.github.chronosx88.yggdrasil.YggdrasilTunService.access$readPacketsFromTun(YggdrasilTunService.kt:31)
	at io.github.chronosx88.yggdrasil.YggdrasilTunService$setupTunInterface$1.invoke(YggdrasilTunService.kt:128)
	at io.github.chronosx88.yggdrasil.YggdrasilTunService$setupTunInterface$1.invoke(YggdrasilTunService.kt:125)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by vikulin** [comment]
Closed.
